apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: postgres-deployment
  labels:
    deploy: middle-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgresapp
      tier: middle 
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgresapp
        tier: middle 
    spec:
      containers:
        - name: postgres-pod
          image: postgres 
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
          resources:
            limits:
              cpu: "500m"
              memory: "100Mi"
            requests:
              cpu: "100m"
              memory: "50Mi"