apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: {{ .Release.Name }}-postgresapp
  labels:
    deploy: middle-deployment
spec:
  replicas: {{ .Values.postgresdeployment.replicas }}
  selector:
    matchLabels:
      name: postgresapp
      tier: middle 
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgresapp
        tier: middle 
    spec:
      containers:
        - name: postgres-pod
          image: {{ .Values.postgresdeployment.image.repository }} 
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_HOST_AUTH_METHOD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_HOST_AUTH_METHOD
          resources:
            limits:
              cpu: "999m"
              memory: "900Mi"
            requests:
              cpu: "500m"
              memory: "500Mi"