apiVersion: v1 
kind: Service 
metadata:
  name: {{ .Values.postgresdeployment.service.name }}
  labels:
    name: postgres-service
    tier: middle
spec:
  selector:
    name: postgresapp
    tier: middle
  ports:
    - port: 5432
      targetPort: 5432