apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: {{ .Release.Name }}-redisapp
  labels:
    deploy: middle-deployment
spec:
  replicas: {{ .Values.redisdeployment.replicas }}
  selector:
    matchLabels:
      name: redisapp
      tier: middle
  template:
    metadata:
      name: redis-pod
      labels: 
        name: redisapp
        tier: middle
    spec:
      containers:
        - name: redis-container
          image: {{ .Values.redisdeployment.image.repository }}
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "500m"
              memory: "100Mi"
            requests:
              cpu: "100m"
              memory: "50Mi"