apiVersion: apps/v1
kind: Deployment 
metadata:
  name: {{ .Release.Name }}-resultapp
  labels: 
    deploy: front-end-application
spec:
  replicas: {{ .Values.resultappdeployment.replicas }}
  selector:
    matchLabels:
      name: resultapp
      tier: front-end
  template: 
    metadata:
      name: resultapp-pod
      labels:
        name: resultapp
        tier: front-end
    spec:
      containers:
        - name: resultapp-pod
          image: "{{ .Values.resultappdeployment.image.repository }}:{{ .Values.resultappdeployment.image.tag }}"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /live
              port: 80
          resources:
            limits:
              cpu: "500m"
              memory: "100Mi"
            requests:
              cpu: "250m"
              memory: "50Mi"
