apiVersion: v1
kind: Service 
metadata:
  name: {{ .Release.Name }}-votingappservice
spec:
  type: {{ .Values.votingapp.service.type }}
  selector:
    name: votingapp
    tier: front-end
  ports:
    - port: 80
      targetPort: 80