apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: {{ .Release.Name }}workerapp
  labels:
    tier: backend-deployment
spec:
  replicas: {{ .Values.workerappdeployment.replicas }}
  selector:
    matchLabels:
      name: workerapp
      tier: middle
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: workerapp
        tier: middle
    spec:
      containers:
        - name: worker-app-container
          image: "{{ .Values.workerappdeployment.image.repository }}:{{ .Values.workerappdeployment.image.tag }}"
          livenessProbe:
            httpGet:
              path: /live
              port: 80
          resources:
            limits:
              cpu: "500m"
              memory: "100Mi"
            requests:
              cpu: "100m"
              memory: "50Mi"